name: fire_detection_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.1
  http: ^1.2.2
  intl: ^0.19.0
  shared_preferences: ^2.3.1

dev_dependencies:
  flutter_lints: ^3.0.0
  device_preview: ^1.2.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: AvenirArabic
      fonts:
        - asset: assets/fonts/avenirArabic/AvenirArabic-Black.otf
        - asset: assets/fonts/avenirArabic/AvenirArabic-Book.otf
        - asset: assets/fonts/avenirArabic/AvenirArabic-Heavy.otf
        - asset: assets/fonts/avenirArabic/AvenirArabic-Light.otf
        - asset: assets/fonts/avenirArabic/AvenirArabic-Light1.otf
        - asset: assets/fonts/avenirArabic/AvenirArabic-Medium.otf

flutter_intl:
  enabled: true
